apps/usuario/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.usuario.views import RegistroUsuario, ListarUsuario, EliminarUsuario,\
RegistrarRequisito,ListarRequisito, EditarRequisito ,EliminarRequisito , RegistroRS, ListarRS,\
EditarRS, EliminarRS, UserProfileUpdateView

urlpatterns = [
    url(r'^registrar', login_required(RegistroUsuario.as_view()), name='registrar'),
    url(r'^listar', login_required(ListarUsuario.as_view()), name='listar'),
    # url(r'^editar/(?P<pk>\d+)/$', login_required(EditarUsuario.as_view()), name='editar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(UserProfileUpdateView.as_view()), name='editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(EliminarUsuario.as_view()), name='eliminar'),
    
    url(r'^requisito/rs/registrar/', login_required(RegistrarRequisito.as_view()), name='registrar_requisitoRS'),
    url(r'^requisito/rs/listar/', login_required(ListarRequisito.as_view()), name='listar_requisitoRS'),
    url(r'^requisito/editar/(?P<pk>\d+)/$', login_required(EditarRequisito.as_view()), name='editar_requisito'),
    url(r'^requisito/eliminar/(?P<pk>\d+)/$', login_required(EliminarRequisito.as_view()), name='eliminar_requisito'),
    
    url(r'^razon_social/registrar/', login_required(RegistroRS.as_view()), name='registrar_razon_social'),
    url(r'^razon_social/listar/', login_required(ListarRS.as_view()), name='listar_razon_social'),
    url(r'^razon_social/editar/(?P<pk>\d+)/$', login_required(EditarRS.as_view()), name='editar_razon_social'),
    url(r'^razon_social/eliminar/(?P<pk>\d+)/$', login_required(EliminarRS.as_view()), name='eliminar_razon_social'),
]

sit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.urls import path
from django.contrib.auth.views import login, logout_then_login

from django.contrib.auth.decorators import login_required
from apps.tramite.home import Index
from axes.decorators import watch_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', (Index.as_view()), name='home'),
    url(r'^tramite/', include('apps.tramite.urls', namespace="tramite")),
    url(r'^vehiculo/', include('apps.vehiculo.urls', namespace="vehiculo")),
    url(r'^operador/', include('apps.operario.urls', namespace="operario")),
    url(r'^tecnico/', include('apps.tecnico.urls', namespace="tecnico")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # url(r'^accounts/login/', login,{'template_name':'index.html'}, name='login'),
    url(r'^accounts/login/$', watch_login(login),{'template_name':'index.html'}, name='login'),
    url(r'^logout/', watch_login(logout_then_login), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

apps/usuario/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/usuario/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView
from django.core.urlresolvers import reverse_lazy

from apps.operario.models import Requisitos_RS, Razon_Social
 
from apps.usuario.form import RegistroForm, RazonSForm, RequisitosRSForm, UserProfileForm
# Create your views here.
class RegistroUsuario(CreateView):
    model = User
    template_name = 'usuario/registrar.html'
    form_class = RegistroForm
    success_url = reverse_lazy('usuario:listar')

class ListarUsuario(ListView):
    model = User
    template_name = 'usuario/listar.html'

class UserProfileUpdateView(UpdateView):
    model = User
    template_name = 'usuario/actualizar.html'
    success_url = reverse_lazy('usuario:listar')
    def get_initial(self):
        initial = super(UserProfileUpdateView, self).get_initial()
        try:
            current_group = self.object.groups.get()
        except:
            # puede ocurrir una excepción si el usuario editado no tiene grupos o tiene más de un grupo 
            # exception can occur if the edited user has no groups
            # or has more than one group
            pass
        else:
            initial['group'] = current_group.pk
        return initial
    
    def get_form_class(self):
        return UserProfileForm
    
    def form_valid(self, form):
        self.object.groups.clear()
        self.object.groups.add(form.cleaned_data['group'])
        return super(UserProfileUpdateView, self).form_valid(form)

class EliminarUsuario(DeleteView):
    model = User
    template_name = 'usuario/eliminar.html'
    success_url = reverse_lazy('usuario:listar')

#Requisitos Razon Social
class RegistrarRequisito(CreateView):
    model = Requisitos_RS
    template_name = 'usuario/requisito_razon_social_form.html'
    form_class = RequisitosRSForm
    success_url = reverse_lazy('usuario:listar_requisitoRS')

class ListarRequisito(ListView):
    model = Requisitos_RS
    template_name = 'usuario/requisito_razon_social_listar.html'

class EditarRequisito(UpdateView):
    model = Requisitos_RS
    template_name = 'usuario/requisito_razon_social_form.html'
    form_class = RequisitosRSForm
    success_url = reverse_lazy('usuario:listar_requisitoRS')

class EliminarRequisito(DeleteView):
    model = Requisitos_RS
    template_name = 'usuario/eliminar_requisito.html'
    success_url = reverse_lazy('usuario:listar_requisitoRS')

#Razon Social
class RegistroRS(CreateView):
    model = Razon_Social
    template_name = 'usuario/registrar_razon_social.html'
    form_class = RazonSForm
    success_url = reverse_lazy('usuario:listar_razon_social')

class ListarRS(ListView):
    model = Razon_Social
    template_name = 'usuario/listar_razon_social.html'

class EditarRS(UpdateView):
    model = Razon_Social
    template_name = 'usuario/registrar_razon_social.html'
    form_class = RazonSForm
    success_url = reverse_lazy('usuario:listar_razon_social')

class EliminarRS(DeleteView):
    model = Razon_Social
    template_name = 'usuario/eliminar_razon_social.html'
    success_url = reverse_lazy('usuario:listar_razon_social')

templates/usuario/eliminar.html
{% extends "base/base_site.html" %}

{% block title %} Delete User {% endblock title %}

{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h1>ELIMINAR USUARIO</h1>
          <div class="clearfix"></div>
        </div>
          <form method= "post" data-parsley-validate class="form-horizontal form-label-left">
            {% csrf_token %}
            <div class="row">
              <div class="form-group col-md-12 col-sm-12 col-xs-12">
              </div>
              <h3>¿Desea eliminar al usuario {{ object.first_name }}?</h3>
              <div class="ln_solid col-md-12 col-sm-12 col-xs-12"></div>
              <div class="form-group col-md-8 col-sm-12 col-xs-12">
                <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-3">
                  <a class="btn btn-default volver-detalle" href="#">Cancelar</a>
                  <button type="submit" class="btn btn-danger">Si, Eliminar</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <script src="/static/js/project.js"></script>
  <!-- validator -->
  <script src="/static/vendors/validator/validator.js"></script>
{% endblock %}

templates/usuario/eliminar_razon_social.html
{% extends "base/base_site.html" %}

{% block title %} Delete Razon Social {% endblock title %}

{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h1>ELIMINAR RAZON SOCIAL</h1>
          <div class="clearfix"></div>
        </div>
          <form method= "post" data-parsley-validate class="form-horizontal form-label-left">
            {% csrf_token %}
            <div class="row">
              <div class="form-group col-md-12 col-sm-12 col-xs-12">
              </div>
                <h3>¿Desea eliminar a {{ object.nombre }}?</h3>
                <br>
                <div class="alert alert-danger alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">x</span>
                    </button>
                    <strong>Advertencia!!!</strong>
                    Si borra este item, tambien se borraran los items asociados a mismo
                </div>
              <div class="ln_solid col-md-12 col-sm-12 col-xs-12"></div>
              <div class="form-group col-md-8 col-sm-12 col-xs-12">
                <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-3">
                  <a class="btn btn-default volver-detalle" href="{% url 'usuario:listar_razon_social' %}">Cancelar</a>
                  <button type="submit" class="btn btn-danger">Si, Eliminar</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <script src="/static/js/project.js"></script>
  <!-- validator -->
  <script src="/static/vendors/validator/validator.js"></script>
{% endblock %}

templates/usuario/listar.html
{% extends "base/base_site.html" %}

{% block title %} List User {% endblock title %}

{% block content %}
<div class="right_col" role="main">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <h1 style="text-align:center">Lista de Usuarios</h1>
            <div class="x_content">
                <div class="">
                    <div class="">
                        <div class="" role="tabpanel" data-example-id="togglable-tabs">
                          <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                            <li role="presentation" class="active">
                              <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">
                                <label class="form-label">Usuarios</label>
                                <span class="badge bg-blue">{{object_list.count}}</span>
                              </a>
                            </li>
                          </ul>
                          <div id="myTabContent" class="tab-content">
                            <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                              <p>
                                <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                                  <div class="row">
                                    <div class="col-sm-12">
                                      <div class="table-responsive">
                                      <!-- <table class="table table-striped table-bordered prueba dt-responsive display nowrap jambo_table" cellpadding="0" width="100%"> -->
                                      <table class="table table-bordered jambo_table" cellpadding="0" width="100%">
                                        <thead>
                                          <tr class="headings" >
                                            <th>ID</th>
                                            <th>ACCION</th>
                                            <th>NOMBRE DE USUARIO</th>
                                            <th>NOMBRE</th>
                                            <th>APELLIDOS</th>
                                            <th>EMAIL</th>
                                          </tr>
                                        </thead>
                                        <tbody>
                                            {% if object_list %}
                                              {% for user in object_list %}
                                              <tr>
                                                    <td>{{ user.id }}</td>
                                                    <td>
                                                        <a class="btn btn-round btn-primary btn-xs" data-toggle="tooltip" title="Editar" href="{% url 'usuario:editar' pk=user.id %}"><i class="fa fa-pencil"></i></a>
                                                        <a class="btn btn-round btn-danger btn-xs " data-toggle="tooltip" title="Eliminar" href="{% url 'usuario:eliminar' pk=user.id %}"><i class="fa fa-trash"></i></a>
                                                    </td>
                                                    <td>{{ user.username }}</td>
                                                    <td>{{ user.first_name }}</td>
                                                    <td>{{ user.last_name }}</td>
                                                    <td>{{ user.email }}</td>
                                              </tr>
                                              {% endfor %}
                                            {% else %}
                                              <h1>No hay trámites nuevos</h1>
                                            {% endif %}
                                        </tbody>
                                      </table>
                                    </div>
                                    </div>
                                  </div>
                                </div>
                              <p>
                                <a class="btn btn-app" href="{% url 'usuario:registrar' %}"><i class="fa fa-edit"></i>Registrar Usuario</a>
                              </p>
                              </p>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block javascripts %}
  {{ block.super }}
    <script src="/static/js/project.js"></script>
    <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/static/js/responsive.bootstrap.js"></script>
    <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <!-- validator -->
    <script src="/static/vendors/validator/validator.js"></script>
    <script type="text/javascript">

        $('a[data-toggle="tab"]').on( 'shown.bs.tab', function (e) {
                //$.fn.dataTable.tables( {visible: true, api: true} ).columns.adjust();
            $.fn.dataTable.tables({ visible: true, api: true }).columns.adjust();
        } );
        $('.prueba').DataTable( {
          "scrollY":        "300px",
          "scrollCollapse": true,
          "paging":         true,
          "responsive":     true,
          "ordering":       true,
          "language": {
              "sProcessing":     "Procesando...",
              "sLengthMenu":     "Mostrar _MENU_ registros",
              "sZeroRecords":    "No se encontraron resultados",
              "sEmptyTable":     "Ningún dato disponible en esta tabla",
              "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
              "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
              "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
              "sInfoPostFix":    "",
              "sSearch":         "Buscar:",
              "sUrl":            "",
              "sInfoThousands":  ",",
              "sLoadingRecords": "Cargando...",
              "oPaginate": {
                  "sFirst":    "Primero",
                  "sLast":     "Último",
                  "sNext":     "Siguiente",
                  "sPrevious": "Anterior"
              },
              "oAria": {
                  "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                  "sSortDescending": ": Activar para ordenar la columna de manera descendente"
              }
          }
        } );
    </script>
      <style type="text/css">
      .prueba{
        height: 150px;
      }
      </style>
{% endblock %}

templates/usuario/listar_razon_social.html
{% extends "base/base_site.html" %}

{% block title %} List Razon Social {% endblock title %}

{% block content %}
<div class="right_col" role="main">
  <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
            <h1 style="text-align:center">Lista Razon Social</h1>
            <div class="x_content">
                <div class="">
                    <div class="">
                        <div class="" role="tabpanel" data-example-id="togglable-tabs">
                          <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                            <li role="presentation" class="active">
                              <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">
                                <label class="form-label">Razon Soacial</label>
                                <span class="badge bg-blue">{{object_list.count}}</span>
                              </a>
                            </li>
                          </ul>
                          <div id="myTabContent" class="tab-content">
                            <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                              <p>
                                <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                                  <div class="row">
                                    <div class="col-sm-12">
                                      <table class="table table-striped table-bordered prueba dt-responsive display nowrap jambo_table" cellpadding="0" width="100%">
                                        <thead>
                                          <tr class="headings" >
                                            <th>ID</th>
                                            <th>NOMBRE</th>
                                            <th>REQUISITOS</th>
                                            <th>ACCION</th>
                                          </tr>
                                        </thead>
                                        <tbody>
                                            {% if object_list %}
                                              {% for razon_social in object_list %}
                                              <tr>
                                                    <td>{{ razon_social.id }}</td>
                                                    <td>{{ razon_social.nombre }}</td>
                                                    <td>{{ razon_social.requisitos }}</td>
                                                    <td>
                                                        <a class="btn btn-round btn-primary btn-xs" data-toggle="tooltip" title="Editar" href="{% url 'usuario:editar_razon_social' pk=razon_social.id %}"><i class="fa fa-pencil"></i></a>
                                                        <a class="btn btn-round btn-danger btn-xs " data-toggle="tooltip" title="Eliminar" href="{% url 'usuario:eliminar_razon_social' pk=razon_social.id %}"><i class="fa fa-trash"></i></a>
                                                    </td>
                                              </tr>
                                              {% endfor %}
                                            {% else %}
                                              <h1>No hay trámites nuevos</h1>
                                            {% endif %}
                                        </tbody>
                                      </table>
                                    </div>
                                  </div>
                                </div>
                                <p>
                                  <a class="btn btn-app" href="{% url 'usuario:registrar_razon_social' %}"><i class="fa fa-edit"></i>Registrar Razón Social</a>
                                </p>
                              </p>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block javascripts %}
  {{ block.super }}
    <script src="/static/js/project.js"></script>
    <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/static/js/responsive.bootstrap.js"></script>
    <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <!-- validator -->
    <script src="/static/vendors/validator/validator.js"></script>
    <script type="text/javascript">

        $('a[data-toggle="tab"]').on( 'shown.bs.tab', function (e) {
                //$.fn.dataTable.tables( {visible: true, api: true} ).columns.adjust();
            $.fn.dataTable.tables({ visible: true, api: true }).columns.adjust();
        } );
        $('.prueba').DataTable( {
          "scrollY":        "300px",
          "scrollCollapse": true,
          "paging":         true,
          "responsive":     true,
          "ordering":       true,
          "language": {
              "sProcessing":     "Procesando...",
              "sLengthMenu":     "Mostrar _MENU_ registros",
              "sZeroRecords":    "No se encontraron resultados",
              "sEmptyTable":     "Ningún dato disponible en esta tabla",
              "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
              "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
              "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
              "sInfoPostFix":    "",
              "sSearch":         "Buscar:",
              "sUrl":            "",
              "sInfoThousands":  ",",
              "sLoadingRecords": "Cargando...",
              "oPaginate": {
                  "sFirst":    "Primero",
                  "sLast":     "Último",
                  "sNext":     "Siguiente",
                  "sPrevious": "Anterior"
              },
              "oAria": {
                  "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                  "sSortDescending": ": Activar para ordenar la columna de manera descendente"
              }
          }
        } );
    </script>
      <style type="text/css">
      .prueba{
        height: 150px;
      }
      </style>
{% endblock %}

templates/usuario/requisito_razon_social_listar.html
{% extends "base/base_site.html" %}

{% block title %} List Razon Social {% endblock title %}

{% block content %}
<div class="right_col" role="main">
  <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
            <h1 style="text-align:center">Lista de Requisitos por Razon Social</h1>
            <div class="x_content">
                <div class="">
                    <div class="">
                        <div class="" role="tabpanel" data-example-id="togglable-tabs">
                          <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                            <li role="presentation" class="active">
                              <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">
                                <label class="form-label">Requisitos</label>
                                <span class="badge bg-blue">{{object_list.count}}</span>
                              </a>
                            </li>
                          </ul>
                          <div id="myTabContent" class="tab-content">
                            <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                              <p>
                                <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                                  <div class="row">
                                    <div class="col-sm-12">
                                      <table class="table table-striped table-bordered prueba dt-responsive display nowrap jambo_table" cellpadding="0" width="100%">
                                        <thead>
                                          <tr class="headings" >
                                            <th>ID</th>
                                            <th>DESCRIPCION</th>
                                            <th>ACCION</th>
                                          </tr>
                                        </thead>
                                        <tbody>
                                            {% if object_list %}
                                              {% for requisito in object_list %}
                                              <tr>
                                                    <td>{{ requisito.id }}</td>
                                                    <td>{{ requisito.descripcion }}</td>
                                                    <td>
                                                        <a class="btn btn-round btn-primary btn-xs" data-toggle="tooltip" title="Editar" href="{% url 'usuario:editar_requisito' pk=requisito.id %}"><i class="fa fa-pencil"></i></a>
                                                        <a class="btn btn-round btn-danger btn-xs " data-toggle="tooltip" title="Eliminar" href="{% url 'usuario:eliminar_requisito' pk=requisito.id %}"><i class="fa fa-trash"></i></a>
                                                    </td>
                                              </tr>
                                              {% endfor %}
                                            {% else %}
                                              <h1>No hay trámites nuevos</h1>
                                            {% endif %}
                                        </tbody>
                                      </table>
                                    </div>
                                  </div>
                                </div>
                                <p>
                                  <a class="btn btn-app" href="{% url 'usuario:registrar_requisitoRS' %}"><i class="fa fa-edit"></i>Registrar Nuevo Requisito</a>
                                </p>
                              </p>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block javascripts %}
  {{ block.super }}
    <script src="/static/js/project.js"></script>
    <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/static/js/responsive.bootstrap.js"></script>
    <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <!-- validator -->
    <script src="/static/vendors/validator/validator.js"></script>
    <script type="text/javascript">

        $('a[data-toggle="tab"]').on( 'shown.bs.tab', function (e) {
                //$.fn.dataTable.tables( {visible: true, api: true} ).columns.adjust();
            $.fn.dataTable.tables({ visible: true, api: true }).columns.adjust();
        } );
        $('.prueba').DataTable( {
          "scrollY":        "300px",
          "scrollCollapse": true,
          "paging":         true,
          "responsive":     true,
          "ordering":       true,
          "language": {
              "sProcessing":     "Procesando...",
              "sLengthMenu":     "Mostrar _MENU_ registros",
              "sZeroRecords":    "No se encontraron resultados",
              "sEmptyTable":     "Ningún dato disponible en esta tabla",
              "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
              "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
              "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
              "sInfoPostFix":    "",
              "sSearch":         "Buscar:",
              "sUrl":            "",
              "sInfoThousands":  ",",
              "sLoadingRecords": "Cargando...",
              "oPaginate": {
                  "sFirst":    "Primero",
                  "sLast":     "Último",
                  "sNext":     "Siguiente",
                  "sPrevious": "Anterior"
              },
              "oAria": {
                  "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                  "sSortDescending": ": Activar para ordenar la columna de manera descendente"
              }
          }
        } );
    </script>
      <style type="text/css">
      .prueba{
        height: 150px;
      }
      </style>
{% endblock %}