apps/tecnico/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.contrib import admin

from apps.tecnico.views import OperarioNuevoCreate, ListarOperarioN, OperarioNuevoDetail, CrearVehiculoN,\
EditarVehiculoN, EliminarVehivuloN, VerificarOperarioN, VerificarOperario, VerificarVehiculo, NotaCreate,\
NotaEdit, CreateFoto, DeleteFoto, CreateInforme, informeObs, informeDevol, informeTecnico, EmitirDocumentos,\
createDocLegal, generar_inf_legal, generar_res_administrativa, ListarOperadorR, buscar_operador,\
SelectOperadores, RenovarTarjetas, NotaRenovacion, NotaEditRenovacion, AsignarVehiculosRenovacion,\
SeleccionarVehiculoRenovacion, QuitarVehiculoRenovacion, DetalleOperadorRenovacion, VerificarVehiculoRenovacion,\
CreateInformeRenovacion, informeObsRenovando, informeDevol_renovacion, informeTecnico_renovacion,\
crearDocLeg, CreateVehiculoN, CrearFoto, EliminarFoto, EditVehiculoN, DeleteVehivuloN, ListarMarca, CreateMarca,\
DeleteMarca

from apps.tecnico.ajax import test, verifivehiculo

urlpatterns = [
    url(r'^nuevo$', login_required(OperarioNuevoCreate.as_view()), name='operario_nuevo_crear'),
    url(r'^nueva/nota/(?P<pk>\d+)/$', login_required(NotaCreate.as_view()), name='nota_crear'),
    url(r'^editar/nota/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(NotaEdit.as_view()), name='nota_editar'),

    url(r'^listar$', login_required(ListarOperarioN.as_view()), name='operario_nuevo_listar'),
    url(r'^verificar$', login_required(VerificarOperarioN.as_view()), name='operario_nuevo_verificar'),
    url(r'^detalle/(?P<pk>\d+)/$', login_required(OperarioNuevoDetail.as_view()), name='operario_detalle'),

    url(r'^vehiculo_nuevo/(?P<pk>\d+)/$', login_required(CrearVehiculoN.as_view()), name='vehiculo_nuevo_crear'),
    url(r'^vehiculo_nuevo_editar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EditarVehiculoN.as_view()), name='vehiculo_nuevo_editar'),
    url(r'^vehiculo_nuevo_eliminar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EliminarVehivuloN.as_view()), name='vehiculo_nuevo_eliminar'),

    url(r'^verificacion/(?P<pk>\d+)/$', login_required(VerificarOperario.as_view()), name='operador_verificacion'),
    
    url(r'^verifi/(?P<pk>\d+)/$', login_required(VerificarVehiculo.as_view()), name='vehiculo_verificacion'),
    # funciones ajax
    url(r'^prueba$', test, name='prueba'),
    url(r'^verificarvehiculo$', verifivehiculo, name='verificar_vehiculo'),
    # url fotos vehiculos
    url(r'^foto_vehiculo/(?P<pk>\d+)/$', login_required(CreateFoto.as_view()), name='foto_vehiculo'),
    url(r'^foto_eliminar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(DeleteFoto.as_view()), name='foto_eliminar'),

    # url emitir informes
    url(r'^informe/(?P<pk>\d+)/(?P<tip>\d+)/$', login_required(CreateInforme.as_view()), name='emitir_informe'),
    url(r'^informeobs/(?P<pk>\d+)/$', login_required(informeObs.as_view()), name='informe_obs'),
    url(r'^informedevol/(?P<pk>\d+)/$', login_required(informeDevol.as_view()), name='informe_devol'),
    url(r'^informetecnico/(?P<pk>\d+)/$', login_required(informeTecnico.as_view()), name='informe_tecnico'),

    # Documentos Legales
    url(r'^listar/op/documentos/$', login_required(EmitirDocumentos.as_view()), name='listar_op_documentos'),
    url(r'^listar/op/documentos/informelegal/(?P<pk>\d+)/(?P<tip>\d+)/$', login_required(createDocLegal.as_view()), name='doc_legal'),

    url(r'^generar/informelegal/(?P<pk>\d+)/$', login_required(generar_inf_legal), name='generar_informe_legal'),
    url(r'^generar/resadministrativa/(?P<pk>\d+)/$', login_required(generar_res_administrativa), name='generar_resolucion_administrativa'),

    url(r'^listarRenovados$', login_required(ListarOperadorR.as_view()), name='operador_renovavion_listar'),
    # Intento, de poner un operador para renovacion de tarjetas
    url(r'^buscar_operador/$', buscar_operador, name = 'buscar_operador'),
    # fin intento
    url(r'^operadores/$', login_required(SelectOperadores.as_view()), name='seleccionar_operadores'),
    url(r'^renovar/(?P<pk>\d+)/$', login_required(RenovarTarjetas.as_view()), name='renovar_operador'),

    url(r'^nota/(?P<pk>\d+)/$', login_required(NotaRenovacion.as_view()), name='nota_renovar'),
    url(r'^nota/editar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(NotaEditRenovacion.as_view()), name='nota_renovacion_editar'),

    url(r'^asignar/renovacion/(?P<pk>\d+)/$', login_required(AsignarVehiculosRenovacion.as_view()), name='operador_renovacion'),
    url(r'^renovar/vehiculo/(?P<pk>\d+)/$', login_required(SeleccionarVehiculoRenovacion.as_view()), name='vehiculo_renovar'),
    url(r'^quitar/vehiculo/(?P<pk>\d+)/$', login_required(QuitarVehiculoRenovacion.as_view()), name='vehiculo_quitar'),
    url(r'^detalle/renovacion/(?P<pk>\d+)/$', login_required(DetalleOperadorRenovacion.as_view()), name='operador_renovando'),
    url(r'^vehiculo/renovacion/(?P<pk>\d+)/$', login_required(VerificarVehiculoRenovacion.as_view()), name='vehiculo_renovando'),

    url(r'^informe/renovacion/(?P<pk>\d+)/$', login_required(informeObsRenovando.as_view()), name='informe_obs_renovando'),
    url(r'^informe/devolucion/(?P<pk>\d+)/$', login_required(informeDevol_renovacion.as_view()), name='informe_devol_renovando'),
    url(r'^informe/tecnico/(?P<pk>\d+)/$', login_required(informeTecnico_renovacion.as_view()), name='informe_tecnico_renovando'),
    url(r'^informe/r/(?P<pk>\d+)/(?P<tip>\d+)/$', login_required(CreateInformeRenovacion.as_view()), name='emitir_informe_renovacion'),

    url(r'^documento/legal/(?P<pk>\d+)/(?P<tip>\d+)/$', login_required(crearDocLeg.as_view()), name='documento_legal'),

    #Aumetar vehiculos al renovar
    url(r'^nuevo_vehiculo/(?P<pk>\d+)/$', login_required(CreateVehiculoN.as_view()), name='crear_vehiculo_nuevo'),
    url(r'^vehiculo_n_editar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EditVehiculoN.as_view()), name='vehiculo_n_editar'),
    url(r'^vehiculo_n_eliminar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(DeleteVehivuloN.as_view()), name='vehiculo_n_eliminar'),

    url(r'^foto_vehi/(?P<pk>\d+)/$', login_required(CrearFoto.as_view()), name='foto_vehi'),
    url(r'^foto_delete/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EliminarFoto.as_view()), name='eliminar_foto'),
    url(r'^marca/listar/$', login_required(ListarMarca.as_view()), name='listar_marca'),
    url(r'^create_marca/$', login_required(CreateMarca.as_view()), name='crear_marca'),
    url(r'^delete_marca/(?P<pk>\d+)/$', login_required(DeleteMarca.as_view()), name='eliminar_marca'),

]

apps/tramite/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.tramite.home import Index
from apps.tramite.views import CrearTramite, search_operador_nombre,\
ListarTramite, AsignarVehiculos, AsignarVehiculo, search_vehiculo_placa,\
TramiteProceso, ordenDeposito, ListarTarjetas, Tarjetas, TramiteFinalizar,\
EliminarAsignacion, ListarSeguimiento, Seguimiento
# tramite_view, tramite_list_ingresados, seguimiento_view, tramite_search, tramite_encontrar


urlpatterns = [
    url(r'^$', login_required(Index.as_view()), name='index'),
    url(r'^registrar/$', login_required(CrearTramite.as_view()), name='registrar_tramite'),
    url(r'^search_operador_nombre/$', search_operador_nombre, name = 'search_operador_nombre'),
    url(r'^listar/$', login_required(ListarTramite.as_view()), name='listar_tramite'),
    url(r'^asignarvehiculos/(?P<pk>\d+)/$', login_required(AsignarVehiculos.as_view()), name='asignar_vehiculos'),
    url(r'^asignarvehiculo/(?P<pk>\d+)/$', login_required(AsignarVehiculo.as_view()), name='asignar_vehiculo'),
    url(r'^asignacion/eliminar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EliminarAsignacion.as_view()), name='eliminar_asignacion'),
    url(r'^tramiteproceso/(?P<pk>\d+)/$', login_required(TramiteProceso.as_view()), name='tramite_proceso'),
    url(r'^search_vehiculo_placa/$', search_vehiculo_placa, name = 'search_vehiculo_placa'),
    url(r'^ordendeposito/(?P<pk>\d+)/$', login_required(ordenDeposito.as_view()), name='orden_deposito'),
    url(r'^tarjetas/(?P<pk>\d+)/$', login_required(ListarTarjetas.as_view()), name='tarjetas'),
    url(r'^imprimir/tarjeta/(?P<pk>\d+)/$', login_required(Tarjetas.as_view()), name='imprimir_tarjeta'),
    url(r'^finalizar/(?P<pk>\d+)/$', login_required(TramiteFinalizar.as_view()), name='tramite_finalizar'),
    url(r'^listar/seguimiento/$', login_required(ListarSeguimiento.as_view()), name='listar_seguimiento'),
    url(r'^seguimiento/(?P<pk>\d+)/$', login_required(Seguimiento.as_view()), name='seguimiento'),
]



# urlpatterns = [
    # url(r'^nuevo$', tramite_view, name='tramite_crear'),
    # url(r'^listar_ingresados$', tramite_list_ingresados, name='tramite_listar_ingresados'),
    # url(r'^seguimiento/(?P<fk>\d+)/$', seguimiento_view, name='seguimiento_crear'),
    # url(r'^buscar$', tramite_search.as_view(), name='buscar_tramite'),
    # url(r'^list_tramite_subjects$', tramite_encontrar.as_view(), name='list_tramite_subjects'),
# ]

sit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.urls import path
from django.contrib.auth.views import login, logout_then_login

from django.contrib.auth.decorators import login_required
from apps.tramite.home import Index
from axes.decorators import watch_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', (Index.as_view()), name='home'),
    url(r'^tramite/', include('apps.tramite.urls', namespace="tramite")),
    url(r'^vehiculo/', include('apps.vehiculo.urls', namespace="vehiculo")),
    url(r'^operador/', include('apps.operario.urls', namespace="operario")),
    url(r'^tecnico/', include('apps.tecnico.urls', namespace="tecnico")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # url(r'^accounts/login/', login,{'template_name':'index.html'}, name='login'),
    url(r'^accounts/login/$', watch_login(login),{'template_name':'index.html'}, name='login'),
    url(r'^logout/', watch_login(logout_then_login), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

templates/tecnico/documento_form.html
{% extends "base/base_site.html" %}

{% block title %} Crear Documento {% endblock title %}

{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>INFORME LEGAL</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <form method= "post" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
            {% csrf_token %}
            <div class="form-group">
              <!-- <label class="control-label col-md-3 col-sm-12 col-xs-12" for="last-name">{{form.descripcion.label}}</label> -->
              <div class="col-md-9 col-sm-12 col-xs-12">
                  {{form.media}}
              </div>
              <div class="col-md-4 col-sm-12 col-xs-12">
                  {{form}}
              </div>
            </div>           
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <a class="btn btn-primary" href="{% url 'tramite:index' %}">CANCELAR</a>
                <button type="submit" class="btn btn-success">REGISTRAR</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <script src="/static/js/project.js"></script>
  <!-- validator -->
  <script src="/static/vendors/validator/validator.js"></script>
{% endblock %}

templates/tecnico/informe_form_renovando.html
{% extends "base/base_site.html" %}

{% block title %} Crear Informe Renovar {% endblock title %}

{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h1>CREAR INFORME</h1>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <form method= "post" data-parsley-validate class="form-horizontal form-label-left">
            {% csrf_token %}
            <div class="row">
                <div class="form-group col-md-12 col-sm-12 col-xs-12">
                    <h2 style="text-decoration : underline">DATOS PREVIOS</h2>
                </div>
                <div class="form-group col-md-6 col-sm-12 col-xs-12">
                    <label class="control-label col-md-4 col-sm-6 col-xs-12">{{form.cite.label}}</label>
                    <div class="col-md-8 col-sm-6 col-xs-12">
                    {{form.cite}}
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12 col-xs-12">
                    <label class="control-label col-md-4 col-sm-6 col-xs-12">{{form.fecha.label}}</label>
                    <div class="col-md-8 col-sm-6 col-xs-12">
                    {{form.fecha}}
                    </div>
                </div>
                {% if analisis %}
                <div class="form-group col-md-12 col-sm-12 col-xs-12">
                    <label class="control-label col-md-2 col-sm-6 col-xs-12">{{form.ans_tecnico.label}}</label>
                    <div class="col-md-10 col-sm-6 col-xs-12">
                    {{form.ans_tecnico}}
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12 col-xs-12">
                    <label class="control-label col-md-2 col-sm-6 col-xs-12">{{form.concluciones.label}}</label>
                    <div class="col-md-10 col-sm-6 col-xs-12">
                    {{form.concluciones}}
                    </div>
                </div>
                {% endif %}
                <div class="ln_solid col-md-12 col-sm-12 col-xs-12"></div>
                <div class="form-group col-md-8 col-sm-12 col-xs-12">
                    <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-3">
                    <a class="btn btn-primary" href="{% url 'tecnico:operador_renovavion_listar' %}">CANCELAR</a>
                    <button type="submit" class="btn btn-success">REGISTRAR</button>
                    </div>
                </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <script src="/static/js/project.js"></script>
  <!-- validator -->
  <script src="/static/vendors/validator/validator.js"></script>
{% endblock %}

templates/tecnico/nota_renovacion.html
{% extends "base/base_site.html" %}

{% block title %} Registro Nota Renovacion {% endblock title %}

{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h1>REGISTRAR LA NOTA</h1>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <form method= "post" data-parsley-validate class="form-horizontal form-label-left">
            {% csrf_token %}
            <div class="row">
              <div class="form-group col-md-12 col-sm-12 col-xs-12">
                <h2 style="text-decoration : underline">DATOS DE LA NOTA</h2>
              </div>
              <div class="form-group col-md-6 col-sm-12 col-xs-12">
                <label class="control-label col-md-4 col-sm-6 col-xs-12">{{form.cite.label}}</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  {{form.cite}}
                </div>
              </div>
              <div class="form-group col-md-6 col-sm-12 col-xs-12">
                <label class="control-label col-md-4 col-sm-6 col-xs-12">{{form.fecha.label}}</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  {{form.fecha}}
                </div>
              </div>
              <div class="form-group col-md-6 col-sm-12 col-xs-12">
                <label class="control-label col-md-4 col-sm-6 col-xs-12">{{form.nombre_ente.label}}</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  {{form.nombre_ente}}
                </div>
              </div>
              <div class="form-group col-md-6 col-sm-12 col-xs-12">
                <label class="control-label col-md-4 col-sm-6 col-xs-12">{{form.representante_ente.label}}</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  {{form.representante_ente}}
                </div>
              </div>
              <div class="form-group col-md-6 col-sm-12 col-xs-12">
                <label class="control-label col-md-4 col-sm-6 col-xs-12">{{form.cargo_repr.label}}</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  {{form.cargo_repr}}
                </div>
              </div>
              <div class="form-group col-md-6 col-sm-12 col-xs-12">
                <label class="control-label col-md-4 col-sm-6 col-xs-12">{{form.ruta_solicitada.label}}</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  {{form.ruta_solicitada}}
                </div>
              </div>
              <div class="form-group col-md-6 col-sm-12 col-xs-12">
                <label class="control-label col-md-4 col-sm-6 col-xs-12">{{form.cantidad_tarjetas.label}}</label>
                <div class="col-md-8 col-sm-6 col-xs-12">
                  {{form.cantidad_tarjetas}}
                </div>
              </div>
              <div class="ln_solid col-md-12 col-sm-12 col-xs-12"></div>
              <div class="form-group col-md-8 col-sm-12 col-xs-12">
                <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-3">
                  <a class="btn btn-primary" href="{% url 'tecnico:operador_renovavion_listar' %}">CANCELAR</a>
                  <button type="submit" class="btn btn-success">REGISTRAR</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <script src="/static/js/project.js"></script>
  <!-- validator -->
  <script src="/static/vendors/validator/validator.js"></script>
{% endblock %}

templates/tecnico/vehiculo_verificar.html
{% extends "base/base_site.html" %}

{% block title %} Verificar Vehículo {% endblock title %}

{% block content %}
<div class="right_col" role="main">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">  
            <div class="x_title">
                <h2>Detalles del Vehículo</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Settings 1</a>
                        </li>
                        <li><a href="#">Settings 2</a>
                        </li>
                    </ul>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="form-group form-horizontal col-md-4 col-sm-12 col-xs-12">
                    <label class="control-label col-md-5 col-sm-6 col-xs-12">Operardor</label>
                    <div class="col-md-7 col-sm-4 col-xs-12">
                        <input class="form-control" type="text" readonly="readonly" placeholder="{{ object.operador }}">
                    </div>
                </div>
                <div class="form-group form-horizontal col-md-4 col-sm-12 col-xs-12">
                    <label class="control-label col-md-2 col-sm-6 col-xs-12">Placa</label>
                    <div class="col-md-10 col-sm-6 col-xs-12">
                        <input class="col-md-12 form-control" type="text" readonly="readonly" placeholder="{{ object.placa }}">
                    </div>
                </div>
                <div class="form-group form-horizontal col-md-4 col-sm-12 col-xs-12">
                    <label class="control-label col-md-4 col-sm-6 col-xs-12">Propietario</label>
                    <div class="col-md-8 col-sm-6 col-xs-12">
                        <input class="col-md-12 form-control" type="text" readonly="readonly" placeholder="{{ object.propietario }}">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Requisitos del Vehículo</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Settings 1</a></li>
                            <li><a href="#">Settings 2</a></li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form class="form-horizontal form-label-left">
                    <div class="form-group">
                        {% for checklist in checklistvehiculos %}
                        <table class="table table-striped table-bordered">
                            <tr>
                                <td>
                                    <div class="checkbox  col-md-12 col-sm-12 col-xs-12">
                                        <label class="col-md-6">{{ checklist.requisitos.descripcion }}</label>
                                        <input class="ids" type="hidden" value="{{ checklist.id }}">
                                        <div class="col-md-5">
                                            {% if checklist.observacion %}
                                                <input type="text" class="observacion" value="{{ checklist.observacion }}" placeholder="Ingrese la obs">
                                            {% else %}
                                                <input type="text" class="observacion" value="" placeholder="Ingrese la observacion">
                                            {% endif %}
                                        </div>
                                        <div class="col-md-1 checkbox">
                                            {% if checklist.cumple %}
                                                <input type="checkbox" class="cumple" checked>
                                            {% else %}
                                                <input type="checkbox" class="cumple">
                                            {% endif %}
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>
                        {% endfor %}
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                            <button type="button" id="boton-enviar" class="btn btn-primary">Guardar Verificación</button>
                            <a class="btn btn-success" href="{% url 'tecnico:operador_verificacion' pk=object.operador.id %}">Verificar otro vehículo</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
    
{% endblock content %}
{% block javascripts %}
    {{ block.super }}
    <script src="/static/js/project.js"></script>
    <!-- validator -->
    <script src="/static/vendors/validator/validator.js"></script>
    
    <script>
        $('#boton-enviar').on('click', function(){
            guardardatos();
        });
        function guardardatos(){
            var lista_obs = [];
            $(".observacion").each(function(){
                lista_obs.push($(this).val());
            });
              
            var list_check = []
            $(".cumple").each(function(){
                list_check.push($(this).prop('checked'));
            });
              
            var list_id = [];
            $(".ids").each(function(){
                list_id.push($(this).val())
            })
    
            $.ajax({
                data: {
                    'lista_obs': JSON.stringify(lista_obs),
                    'lista_check': JSON.stringify(list_check),
                    'list_id': JSON.stringify(list_id),
                },
                url: '{% url "tecnico:verificar_vehiculo" %}',
                type: 'get',
                success: function(data){
                    if (data.response== 'ok'){
                        alert('datos guardados');
                    }
                    else{
                        alert('error al guardar los datos');
                    }
                },
                error: function(mensaje){
                    alert(mensaje);
                }
            });
        }
          
          //   function enviar_ajax(){
          //       var prueba = '123';
          //       $.ajax({
          //           data: {'prueba': prueba},
          //           url: '{% url "tecnico:prueba" %}',
          //           type: 'get',
          //           success: function(data){
          //               if (data.response== 'ok'){
          //                   alert('bien');
          //               }
          //               else{
          //                   alert('mal');
          //               }
          //           },
          //           error: function(mensaje){
          //               alert(mensaje);
          //           }
          //       });
          //   }
    </script>
    
{% endblock %}
        