apps/operario/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.contrib import admin

from apps.operario.views import Listar_Operadores, Registrar_Operador,\
Listar_Detalle_Operadores, Detalle_Operadores, Registrar_Vehiculo,\
CrearRuta, EliminarRuta, Actualizar_Vehiculo, Eliminar_Vehiculo,\
Actualizar_Operador, Eliminar_Operador, ReportAnualOperador

urlpatterns = [
    # url(r'^editar/(?P<pk>\d+)$', RepresentanteUpdate.as_view(), name='operario_editar'),
    # url(r'^listar/operadores/$', login_required(Listar_Operadores.as_view()), name='listar_operadores_nuevos'),
    url(r'^registrar/operador/(?P<pk>\d+)/$', login_required(Registrar_Operador.as_view()), name='registar_operador'),
    url(r'^listar/$', login_required(Listar_Detalle_Operadores.as_view()), name='operador_listar'),
    url(r'^detalle/(?P<pk>\d+)/$', login_required(Detalle_Operadores.as_view()), name='operadores_detalle'),
    url(r'^actualizar/(?P<pk>\d+)/$', login_required(Actualizar_Operador.as_view()), name='operador_actualizar'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(Eliminar_Operador.as_view()), name='operador_eliminar'),

    url(r'^vehiculo/registrar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(Registrar_Vehiculo.as_view()), name='vehiculo_registrar'),
    url(r'^vehiculo/actualizar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(Actualizar_Vehiculo.as_view()), name='vehiculo_actualizar'),
    url(r'^vehiculo/eliminar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(Eliminar_Vehiculo.as_view()), name='vehiculo_eliminar'),
    
    url(r'^ruta/registrar/(?P<pk>\d+)/$', login_required(CrearRuta.as_view()), name='crear_ruta'),
    url(r'^ruta/eliminar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EliminarRuta.as_view()), name='eliminar_ruta'),
    
    url(r'^reporte/anual/$', login_required(ReportAnualOperador.as_view()), name='reporte_anual_operador'),
]

apps/tecnico/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.contrib import admin

from apps.tecnico.views import OperarioNuevoCreate, ListarOperarioN, OperarioNuevoDetail, CrearVehiculoN,\
EditarVehiculoN, EliminarVehivuloN, VerificarOperarioN, VerificarOperario, VerificarVehiculo, NotaCreate,\
NotaEdit, CreateFoto, DeleteFoto, CreateInforme, informeObs, informeDevol, informeTecnico, EmitirDocumentos,\
createDocLegal, generar_inf_legal, generar_res_administrativa, ListarOperadorR, buscar_operador,\
SelectOperadores, RenovarTarjetas, NotaRenovacion, NotaEditRenovacion, AsignarVehiculosRenovacion,\
SeleccionarVehiculoRenovacion, QuitarVehiculoRenovacion, DetalleOperadorRenovacion, VerificarVehiculoRenovacion,\
CreateInformeRenovacion, informeObsRenovando, informeDevol_renovacion, informeTecnico_renovacion,\
crearDocLeg, CreateVehiculoN, CrearFoto, EliminarFoto, EditVehiculoN, DeleteVehivuloN, ListarMarca, CreateMarca,\
DeleteMarca

from apps.tecnico.ajax import test, verifivehiculo

urlpatterns = [
    url(r'^nuevo$', login_required(OperarioNuevoCreate.as_view()), name='operario_nuevo_crear'),
    url(r'^nueva/nota/(?P<pk>\d+)/$', login_required(NotaCreate.as_view()), name='nota_crear'),
    url(r'^editar/nota/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(NotaEdit.as_view()), name='nota_editar'),

    url(r'^listar$', login_required(ListarOperarioN.as_view()), name='operario_nuevo_listar'),
    url(r'^verificar$', login_required(VerificarOperarioN.as_view()), name='operario_nuevo_verificar'),
    url(r'^detalle/(?P<pk>\d+)/$', login_required(OperarioNuevoDetail.as_view()), name='operario_detalle'),

    url(r'^vehiculo_nuevo/(?P<pk>\d+)/$', login_required(CrearVehiculoN.as_view()), name='vehiculo_nuevo_crear'),
    url(r'^vehiculo_nuevo_editar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EditarVehiculoN.as_view()), name='vehiculo_nuevo_editar'),
    url(r'^vehiculo_nuevo_eliminar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EliminarVehivuloN.as_view()), name='vehiculo_nuevo_eliminar'),

    url(r'^verificacion/(?P<pk>\d+)/$', login_required(VerificarOperario.as_view()), name='operador_verificacion'),
    
    url(r'^verifi/(?P<pk>\d+)/$', login_required(VerificarVehiculo.as_view()), name='vehiculo_verificacion'),
    # funciones ajax
    url(r'^prueba$', test, name='prueba'),
    url(r'^verificarvehiculo$', verifivehiculo, name='verificar_vehiculo'),
    # url fotos vehiculos
    url(r'^foto_vehiculo/(?P<pk>\d+)/$', login_required(CreateFoto.as_view()), name='foto_vehiculo'),
    url(r'^foto_eliminar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(DeleteFoto.as_view()), name='foto_eliminar'),

    # url emitir informes
    url(r'^informe/(?P<pk>\d+)/(?P<tip>\d+)/$', login_required(CreateInforme.as_view()), name='emitir_informe'),
    url(r'^informeobs/(?P<pk>\d+)/$', login_required(informeObs.as_view()), name='informe_obs'),
    url(r'^informedevol/(?P<pk>\d+)/$', login_required(informeDevol.as_view()), name='informe_devol'),
    url(r'^informetecnico/(?P<pk>\d+)/$', login_required(informeTecnico.as_view()), name='informe_tecnico'),

    # Documentos Legales
    url(r'^listar/op/documentos/$', login_required(EmitirDocumentos.as_view()), name='listar_op_documentos'),
    url(r'^listar/op/documentos/informelegal/(?P<pk>\d+)/(?P<tip>\d+)/$', login_required(createDocLegal.as_view()), name='doc_legal'),

    url(r'^generar/informelegal/(?P<pk>\d+)/$', login_required(generar_inf_legal), name='generar_informe_legal'),
    url(r'^generar/resadministrativa/(?P<pk>\d+)/$', login_required(generar_res_administrativa), name='generar_resolucion_administrativa'),

    url(r'^listarRenovados$', login_required(ListarOperadorR.as_view()), name='operador_renovavion_listar'),
    # Intento, de poner un operador para renovacion de tarjetas
    url(r'^buscar_operador/$', buscar_operador, name = 'buscar_operador'),
    # fin intento
    url(r'^operadores/$', login_required(SelectOperadores.as_view()), name='seleccionar_operadores'),
    url(r'^renovar/(?P<pk>\d+)/$', login_required(RenovarTarjetas.as_view()), name='renovar_operador'),

    url(r'^nota/(?P<pk>\d+)/$', login_required(NotaRenovacion.as_view()), name='nota_renovar'),
    url(r'^nota/editar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(NotaEditRenovacion.as_view()), name='nota_renovacion_editar'),

    url(r'^asignar/renovacion/(?P<pk>\d+)/$', login_required(AsignarVehiculosRenovacion.as_view()), name='operador_renovacion'),
    url(r'^renovar/vehiculo/(?P<pk>\d+)/$', login_required(SeleccionarVehiculoRenovacion.as_view()), name='vehiculo_renovar'),
    url(r'^quitar/vehiculo/(?P<pk>\d+)/$', login_required(QuitarVehiculoRenovacion.as_view()), name='vehiculo_quitar'),
    url(r'^detalle/renovacion/(?P<pk>\d+)/$', login_required(DetalleOperadorRenovacion.as_view()), name='operador_renovando'),
    url(r'^vehiculo/renovacion/(?P<pk>\d+)/$', login_required(VerificarVehiculoRenovacion.as_view()), name='vehiculo_renovando'),

    url(r'^informe/renovacion/(?P<pk>\d+)/$', login_required(informeObsRenovando.as_view()), name='informe_obs_renovando'),
    url(r'^informe/devolucion/(?P<pk>\d+)/$', login_required(informeDevol_renovacion.as_view()), name='informe_devol_renovando'),
    url(r'^informe/tecnico/(?P<pk>\d+)/$', login_required(informeTecnico_renovacion.as_view()), name='informe_tecnico_renovando'),
    url(r'^informe/r/(?P<pk>\d+)/(?P<tip>\d+)/$', login_required(CreateInformeRenovacion.as_view()), name='emitir_informe_renovacion'),

    url(r'^documento/legal/(?P<pk>\d+)/(?P<tip>\d+)/$', login_required(crearDocLeg.as_view()), name='documento_legal'),

    #Aumetar vehiculos al renovar
    url(r'^nuevo_vehiculo/(?P<pk>\d+)/$', login_required(CreateVehiculoN.as_view()), name='crear_vehiculo_nuevo'),
    url(r'^vehiculo_n_editar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EditVehiculoN.as_view()), name='vehiculo_n_editar'),
    url(r'^vehiculo_n_eliminar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(DeleteVehivuloN.as_view()), name='vehiculo_n_eliminar'),

    url(r'^foto_vehi/(?P<pk>\d+)/$', login_required(CrearFoto.as_view()), name='foto_vehi'),
    url(r'^foto_delete/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EliminarFoto.as_view()), name='eliminar_foto'),
    url(r'^marca/listar/$', login_required(ListarMarca.as_view()), name='listar_marca'),
    url(r'^create_marca/$', login_required(CreateMarca.as_view()), name='crear_marca'),
    url(r'^delete_marca/(?P<pk>\d+)/$', login_required(DeleteMarca.as_view()), name='eliminar_marca'),

]

apps/tramite/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.tramite.home import Index
from apps.tramite.views import CrearTramite, search_operador_nombre,\
ListarTramite, AsignarVehiculos, AsignarVehiculo, search_vehiculo_placa,\
TramiteProceso, ordenDeposito, ListarTarjetas, Tarjetas, TramiteFinalizar,\
EliminarAsignacion, ListarSeguimiento, Seguimiento
# tramite_view, tramite_list_ingresados, seguimiento_view, tramite_search, tramite_encontrar


urlpatterns = [
    url(r'^$', login_required(Index.as_view()), name='index'),
    url(r'^registrar/$', login_required(CrearTramite.as_view()), name='registrar_tramite'),
    url(r'^search_operador_nombre/$', search_operador_nombre, name = 'search_operador_nombre'),
    url(r'^listar/$', login_required(ListarTramite.as_view()), name='listar_tramite'),
    url(r'^asignarvehiculos/(?P<pk>\d+)/$', login_required(AsignarVehiculos.as_view()), name='asignar_vehiculos'),
    url(r'^asignarvehiculo/(?P<pk>\d+)/$', login_required(AsignarVehiculo.as_view()), name='asignar_vehiculo'),
    url(r'^asignacion/eliminar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EliminarAsignacion.as_view()), name='eliminar_asignacion'),
    url(r'^tramiteproceso/(?P<pk>\d+)/$', login_required(TramiteProceso.as_view()), name='tramite_proceso'),
    url(r'^search_vehiculo_placa/$', search_vehiculo_placa, name = 'search_vehiculo_placa'),
    url(r'^ordendeposito/(?P<pk>\d+)/$', login_required(ordenDeposito.as_view()), name='orden_deposito'),
    url(r'^tarjetas/(?P<pk>\d+)/$', login_required(ListarTarjetas.as_view()), name='tarjetas'),
    url(r'^imprimir/tarjeta/(?P<pk>\d+)/$', login_required(Tarjetas.as_view()), name='imprimir_tarjeta'),
    url(r'^finalizar/(?P<pk>\d+)/$', login_required(TramiteFinalizar.as_view()), name='tramite_finalizar'),
    url(r'^listar/seguimiento/$', login_required(ListarSeguimiento.as_view()), name='listar_seguimiento'),
    url(r'^seguimiento/(?P<pk>\d+)/$', login_required(Seguimiento.as_view()), name='seguimiento'),
]



# urlpatterns = [
    # url(r'^nuevo$', tramite_view, name='tramite_crear'),
    # url(r'^listar_ingresados$', tramite_list_ingresados, name='tramite_listar_ingresados'),
    # url(r'^seguimiento/(?P<fk>\d+)/$', seguimiento_view, name='seguimiento_crear'),
    # url(r'^buscar$', tramite_search.as_view(), name='buscar_tramite'),
    # url(r'^list_tramite_subjects$', tramite_encontrar.as_view(), name='list_tramite_subjects'),
# ]

apps/usuario/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.usuario.views import RegistroUsuario, ListarUsuario, EliminarUsuario,\
RegistrarRequisito,ListarRequisito, EditarRequisito ,EliminarRequisito , RegistroRS, ListarRS,\
EditarRS, EliminarRS, UserProfileUpdateView

urlpatterns = [
    url(r'^registrar', login_required(RegistroUsuario.as_view()), name='registrar'),
    url(r'^listar', login_required(ListarUsuario.as_view()), name='listar'),
    # url(r'^editar/(?P<pk>\d+)/$', login_required(EditarUsuario.as_view()), name='editar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(UserProfileUpdateView.as_view()), name='editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(EliminarUsuario.as_view()), name='eliminar'),
    
    url(r'^requisito/rs/registrar/', login_required(RegistrarRequisito.as_view()), name='registrar_requisitoRS'),
    url(r'^requisito/rs/listar/', login_required(ListarRequisito.as_view()), name='listar_requisitoRS'),
    url(r'^requisito/editar/(?P<pk>\d+)/$', login_required(EditarRequisito.as_view()), name='editar_requisito'),
    url(r'^requisito/eliminar/(?P<pk>\d+)/$', login_required(EliminarRequisito.as_view()), name='eliminar_requisito'),
    
    url(r'^razon_social/registrar/', login_required(RegistroRS.as_view()), name='registrar_razon_social'),
    url(r'^razon_social/listar/', login_required(ListarRS.as_view()), name='listar_razon_social'),
    url(r'^razon_social/editar/(?P<pk>\d+)/$', login_required(EditarRS.as_view()), name='editar_razon_social'),
    url(r'^razon_social/eliminar/(?P<pk>\d+)/$', login_required(EliminarRS.as_view()), name='eliminar_razon_social'),
]

sit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.urls import path
from django.contrib.auth.views import login, logout_then_login

from django.contrib.auth.decorators import login_required
from apps.tramite.home import Index
from axes.decorators import watch_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', (Index.as_view()), name='home'),
    url(r'^tramite/', include('apps.tramite.urls', namespace="tramite")),
    url(r'^vehiculo/', include('apps.vehiculo.urls', namespace="vehiculo")),
    url(r'^operador/', include('apps.operario.urls', namespace="operario")),
    url(r'^tecnico/', include('apps.tecnico.urls', namespace="tecnico")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # url(r'^accounts/login/', login,{'template_name':'index.html'}, name='login'),
    url(r'^accounts/login/$', watch_login(login),{'template_name':'index.html'}, name='login'),
    url(r'^logout/', watch_login(logout_then_login), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

templates/base/base_site.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="/static/images/logo.ico" type="image/x-icon">
      {% endblock meta %}

      <title>Gentelella Alela! | {% block title %}{% endblock %}</title>

      {% block stylesheets %}
        <!-- Bootstrap -->
        <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="/static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="/static/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
        <!-- iCheck -->
        <link href="/static/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="/static/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
        <!-- JQVMap -->
        <link href="/static/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
          <!-- PNotify -->
        <link href="/static/vendors/pnotify/dist/pnotify.css" rel="stylesheet">
        <link href="/static/vendors/pnotify/dist/pnotify.buttons.css" rel="stylesheet">
        <link href="/static/vendors/pnotify/dist/pnotify.nonblock.css" rel="stylesheet">
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="/static/build/css/custom.css" rel="stylesheet">
      {% block js %}
      
      {% endblock js %}

    {% endblock head %}
  </head>

  <body class="{% block body_class %}nav-md {% endblock body_class %}">
    {% block body %}
      <div class="container body">
        <div class="main_container">

          {% block sidebar %}
            <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
              {% include "base/sidebar.html" %}
            </div>
          {% endblock sidebar %}

          {% block top_navigation %}
            <div class="top_nav">
              {% include "base/top_navigation.html" %}
            </div>
          {% endblock top_navigation %}

          {% block content %}
            <!-- {{ content }} -->
          {% endblock content %}

          {% block footer %}
            <footer>
              {% include "base/footer.html" %}
            </footer>
          {% endblock footer %}
        </div>
      </div>

      {% block javascripts %}
        <!-- jQuery -->
        <script src="/static/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="/static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="/static/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="/static/vendors/nprogress/nprogress.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="/static/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="/static/vendors/iCheck/icheck.min.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="/static/vendors/moment/min/moment.min.js"></script>
        <script src="/static/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="/static/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js"></script>
        <script src="/static/vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
        <script src="/static/vendors/google-code-prettify/src/prettify.js"></script>
        <!-- jQuery Tags Input -->
        <script src="/static/vendors/jquery.tagsinput/src/jquery.tagsinput.js"></script>
        <!-- Switchery -->
        <script src="/static/vendors/switchery/dist/switchery.min.js"></script>
        <!-- Select2 -->
        <script src="/static/vendors/select2/dist/js/select2.full.min.js"></script>
        <!-- Parsley -->
        <script src="/static/vendors/parsleyjs/dist/parsley.min.js"></script>
        <!-- Autosize -->
        <script src="/static/vendors/autosize/dist/autosize.min.js"></script>
        <!-- jQuery autocomplete -->
        <script src="/static/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
        <!-- starrr -->
        <script src="/static/vendors/starrr/dist/starrr.js"></script>
        <!-- PNotify -->
        <script src="/static/vendors/pnotify/dist/pnotify.js"></script>
        <script src="/static/vendors/pnotify/dist/pnotify.buttons.js"></script>
        <script src="/static/vendors/pnotify/dist/pnotify.nonblock.js"></script>
      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="/static/build/js/custom.js"></script>
    {% endblock body %}
  </body>
</html>

templates/base/footer.html
<div class="pull-right">
  ©2018 SCT - URRT. Todos los derechos reservados.
</div>
<div class="clearfix"></div>

templates/base/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="{% url 'tramite:index' %}" class="site_title"><i class="fa fa-bus"></i> <span>S.C.T.</span></a>
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">
    <div class="profile_pic">
      <img src="/static/images/user.jpg" alt="Avatar" class="img-circle profile_img">
    </div>
    {% if user.is_authenticated %}
      <div class="profile_info">
        <span>Bienvenido!!!</span>
        <h2>{{ request.user|upper }}</h2>
      </div>
    {% else %}
      <div class="profile_info">
        <span>Bienvenido, nuevo usuario. Por favor Inicie Sesión</span> <a style="color:red" href="/">Aquí</a>
      </div>
    {% endif %}
  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <ul class="nav side-menu">
        <li><a href="{% url 'tramite:index' %}"><i class="fa fa-home"></i>Inicio<span class="fa fa-chevron"></span></a></li>
        {% if perms.tecnico.verificar %}
        <li><a><i class="fa fa-edit"></i>VERIFICACION<span class="fa fa-chevron-down"></span></a>  
          <ul class="nav child_menu">
            <li><a href="{% url 'tecnico:operario_nuevo_listar' %}">Nuevo</a></li>
            <li><a href="{% url 'tecnico:operador_renovavion_listar' %}">Renovación</a></li>
            <!-- <li><a href="{# url 'tecnico:operario_nuevo_crear' #}">Registrar</a></li> -->
            <!-- <li><a href="{# url 'tecnico:operario_nuevo_verificar' #}">Verificar</a></li> -->
          </ul>
        </li>
        {% endif %} 
        {% if perms.tecnico.administrar_doc_legal %}
          <li><a><i class="fa fa-file-text-o"></i>DOCUMENTOS<span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="{% url 'tecnico:listar_op_documentos' %}">Generar</a></li>
            </ul>
          </li>
        {% endif %}
        {% if perms.tecnico.administrar_operador %}
          <li><a><i class="fa fa-bus"></i>OPERADORES<span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <!-- <li><a href="{# url 'operario:listar_operadores_nuevos' #}">Registar</a></li> -->
              <li><a href="{% url 'operario:operador_listar' %}">Operadores</a></li>
            </ul>
          </li>
        {% endif %}
        {% if perms.tramite.administrar_tramite %}
          <li><a><i class="fa fa-files-o"></i>TRÁMITES<span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="{% url 'tramite:registrar_tramite' %}">Nuevo Trámite</a></li>
              <li><a href="{% url 'tramite:listar_tramite' %}">Ver Trámites</a></li>
              <li><a href="{% url 'tramite:listar_seguimiento' %}">Seguimiento</a></li>
            </ul>
          </li>
        {% endif %}
        <li><a><i class="fa fa-search"></i>CONSULTAS<span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'vehiculo:listar_vehiculos' %}">Vehículos</a></li>
            <!-- <li><a href="form_validation.html"></a></li> -->
          </ul>
        </li>
        {% if perms.tecnico.emitir_infraccion %}
        <li><a><i class="fa fa-exclamation-triangle"></i>INFRACCIONES<span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'vehiculo:listas_infractores' %}">Infractores</a></li>
          </ul>
        </li>
        {% endif %}
        {% if perms.tecnico.administrador %}
        <li><a><i class="fa fa-gears"></i>ADMINISTRADOR<span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'usuario:listar' %}">Usuario</a></li>
            <li><a href="{% url 'usuario:listar_requisitoRS' %}">Requisitos</a></li>
            <li><a href="{% url 'usuario:listar_razon_social' %}">Razon Social</a></li>
            <li><a href="{% url 'tecnico:listar_marca' %}">Marcas Vehículos</a></li>
          </ul>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->
  <div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="{% url 'logout' %}">
      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
  </div>
  <!-- /menu footer buttons -->
</div>