apps/tecnico/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.contrib import admin

from apps.tecnico.views import OperarioNuevoCreate, ListarOperarioN, OperarioNuevoDetail, CrearVehiculoN,\
EditarVehiculoN, EliminarVehivuloN, VerificarOperarioN, VerificarOperario, VerificarVehiculo, NotaCreate,\
NotaEdit, CreateFoto, DeleteFoto, CreateInforme, informeObs, informeDevol, informeTecnico, EmitirDocumentos,\
createDocLegal, generar_inf_legal, generar_res_administrativa, ListarOperadorR, buscar_operador,\
SelectOperadores, RenovarTarjetas, NotaRenovacion, NotaEditRenovacion, AsignarVehiculosRenovacion,\
SeleccionarVehiculoRenovacion, QuitarVehiculoRenovacion, DetalleOperadorRenovacion, VerificarVehiculoRenovacion,\
CreateInformeRenovacion, informeObsRenovando, informeDevol_renovacion, informeTecnico_renovacion,\
crearDocLeg, CreateVehiculoN, CrearFoto, EliminarFoto, EditVehiculoN, DeleteVehivuloN, ListarMarca, CreateMarca,\
DeleteMarca

from apps.tecnico.ajax import test, verifivehiculo

urlpatterns = [
    url(r'^nuevo$', login_required(OperarioNuevoCreate.as_view()), name='operario_nuevo_crear'),
    url(r'^nueva/nota/(?P<pk>\d+)/$', login_required(NotaCreate.as_view()), name='nota_crear'),
    url(r'^editar/nota/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(NotaEdit.as_view()), name='nota_editar'),

    url(r'^listar$', login_required(ListarOperarioN.as_view()), name='operario_nuevo_listar'),
    url(r'^verificar$', login_required(VerificarOperarioN.as_view()), name='operario_nuevo_verificar'),
    url(r'^detalle/(?P<pk>\d+)/$', login_required(OperarioNuevoDetail.as_view()), name='operario_detalle'),

    url(r'^vehiculo_nuevo/(?P<pk>\d+)/$', login_required(CrearVehiculoN.as_view()), name='vehiculo_nuevo_crear'),
    url(r'^vehiculo_nuevo_editar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EditarVehiculoN.as_view()), name='vehiculo_nuevo_editar'),
    url(r'^vehiculo_nuevo_eliminar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EliminarVehivuloN.as_view()), name='vehiculo_nuevo_eliminar'),

    url(r'^verificacion/(?P<pk>\d+)/$', login_required(VerificarOperario.as_view()), name='operador_verificacion'),
    
    url(r'^verifi/(?P<pk>\d+)/$', login_required(VerificarVehiculo.as_view()), name='vehiculo_verificacion'),
    # funciones ajax
    url(r'^prueba$', test, name='prueba'),
    url(r'^verificarvehiculo$', verifivehiculo, name='verificar_vehiculo'),
    # url fotos vehiculos
    url(r'^foto_vehiculo/(?P<pk>\d+)/$', login_required(CreateFoto.as_view()), name='foto_vehiculo'),
    url(r'^foto_eliminar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(DeleteFoto.as_view()), name='foto_eliminar'),

    # url emitir informes
    url(r'^informe/(?P<pk>\d+)/(?P<tip>\d+)/$', login_required(CreateInforme.as_view()), name='emitir_informe'),
    url(r'^informeobs/(?P<pk>\d+)/$', login_required(informeObs.as_view()), name='informe_obs'),
    url(r'^informedevol/(?P<pk>\d+)/$', login_required(informeDevol.as_view()), name='informe_devol'),
    url(r'^informetecnico/(?P<pk>\d+)/$', login_required(informeTecnico.as_view()), name='informe_tecnico'),

    # Documentos Legales
    url(r'^listar/op/documentos/$', login_required(EmitirDocumentos.as_view()), name='listar_op_documentos'),
    url(r'^listar/op/documentos/informelegal/(?P<pk>\d+)/(?P<tip>\d+)/$', login_required(createDocLegal.as_view()), name='doc_legal'),

    url(r'^generar/informelegal/(?P<pk>\d+)/$', login_required(generar_inf_legal), name='generar_informe_legal'),
    url(r'^generar/resadministrativa/(?P<pk>\d+)/$', login_required(generar_res_administrativa), name='generar_resolucion_administrativa'),

    url(r'^listarRenovados$', login_required(ListarOperadorR.as_view()), name='operador_renovavion_listar'),
    # Intento, de poner un operador para renovacion de tarjetas
    url(r'^buscar_operador/$', buscar_operador, name = 'buscar_operador'),
    # fin intento
    url(r'^operadores/$', login_required(SelectOperadores.as_view()), name='seleccionar_operadores'),
    url(r'^renovar/(?P<pk>\d+)/$', login_required(RenovarTarjetas.as_view()), name='renovar_operador'),

    url(r'^nota/(?P<pk>\d+)/$', login_required(NotaRenovacion.as_view()), name='nota_renovar'),
    url(r'^nota/editar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(NotaEditRenovacion.as_view()), name='nota_renovacion_editar'),

    url(r'^asignar/renovacion/(?P<pk>\d+)/$', login_required(AsignarVehiculosRenovacion.as_view()), name='operador_renovacion'),
    url(r'^renovar/vehiculo/(?P<pk>\d+)/$', login_required(SeleccionarVehiculoRenovacion.as_view()), name='vehiculo_renovar'),
    url(r'^quitar/vehiculo/(?P<pk>\d+)/$', login_required(QuitarVehiculoRenovacion.as_view()), name='vehiculo_quitar'),
    url(r'^detalle/renovacion/(?P<pk>\d+)/$', login_required(DetalleOperadorRenovacion.as_view()), name='operador_renovando'),
    url(r'^vehiculo/renovacion/(?P<pk>\d+)/$', login_required(VerificarVehiculoRenovacion.as_view()), name='vehiculo_renovando'),

    url(r'^informe/renovacion/(?P<pk>\d+)/$', login_required(informeObsRenovando.as_view()), name='informe_obs_renovando'),
    url(r'^informe/devolucion/(?P<pk>\d+)/$', login_required(informeDevol_renovacion.as_view()), name='informe_devol_renovando'),
    url(r'^informe/tecnico/(?P<pk>\d+)/$', login_required(informeTecnico_renovacion.as_view()), name='informe_tecnico_renovando'),
    url(r'^informe/r/(?P<pk>\d+)/(?P<tip>\d+)/$', login_required(CreateInformeRenovacion.as_view()), name='emitir_informe_renovacion'),

    url(r'^documento/legal/(?P<pk>\d+)/(?P<tip>\d+)/$', login_required(crearDocLeg.as_view()), name='documento_legal'),

    #Aumetar vehiculos al renovar
    url(r'^nuevo_vehiculo/(?P<pk>\d+)/$', login_required(CreateVehiculoN.as_view()), name='crear_vehiculo_nuevo'),
    url(r'^vehiculo_n_editar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EditVehiculoN.as_view()), name='vehiculo_n_editar'),
    url(r'^vehiculo_n_eliminar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(DeleteVehivuloN.as_view()), name='vehiculo_n_eliminar'),

    url(r'^foto_vehi/(?P<pk>\d+)/$', login_required(CrearFoto.as_view()), name='foto_vehi'),
    url(r'^foto_delete/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EliminarFoto.as_view()), name='eliminar_foto'),
    url(r'^marca/listar/$', login_required(ListarMarca.as_view()), name='listar_marca'),
    url(r'^create_marca/$', login_required(CreateMarca.as_view()), name='crear_marca'),
    url(r'^delete_marca/(?P<pk>\d+)/$', login_required(DeleteMarca.as_view()), name='eliminar_marca'),

]

apps/tramite/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.tramite.home import Index
from apps.tramite.views import CrearTramite, search_operador_nombre,\
ListarTramite, AsignarVehiculos, AsignarVehiculo, search_vehiculo_placa,\
TramiteProceso, ordenDeposito, ListarTarjetas, Tarjetas, TramiteFinalizar,\
EliminarAsignacion, ListarSeguimiento, Seguimiento
# tramite_view, tramite_list_ingresados, seguimiento_view, tramite_search, tramite_encontrar


urlpatterns = [
    url(r'^$', login_required(Index.as_view()), name='index'),
    url(r'^registrar/$', login_required(CrearTramite.as_view()), name='registrar_tramite'),
    url(r'^search_operador_nombre/$', search_operador_nombre, name = 'search_operador_nombre'),
    url(r'^listar/$', login_required(ListarTramite.as_view()), name='listar_tramite'),
    url(r'^asignarvehiculos/(?P<pk>\d+)/$', login_required(AsignarVehiculos.as_view()), name='asignar_vehiculos'),
    url(r'^asignarvehiculo/(?P<pk>\d+)/$', login_required(AsignarVehiculo.as_view()), name='asignar_vehiculo'),
    url(r'^asignacion/eliminar/(?P<pk>\d+)/(?P<fk>\d+)/$', login_required(EliminarAsignacion.as_view()), name='eliminar_asignacion'),
    url(r'^tramiteproceso/(?P<pk>\d+)/$', login_required(TramiteProceso.as_view()), name='tramite_proceso'),
    url(r'^search_vehiculo_placa/$', search_vehiculo_placa, name = 'search_vehiculo_placa'),
    url(r'^ordendeposito/(?P<pk>\d+)/$', login_required(ordenDeposito.as_view()), name='orden_deposito'),
    url(r'^tarjetas/(?P<pk>\d+)/$', login_required(ListarTarjetas.as_view()), name='tarjetas'),
    url(r'^imprimir/tarjeta/(?P<pk>\d+)/$', login_required(Tarjetas.as_view()), name='imprimir_tarjeta'),
    url(r'^finalizar/(?P<pk>\d+)/$', login_required(TramiteFinalizar.as_view()), name='tramite_finalizar'),
    url(r'^listar/seguimiento/$', login_required(ListarSeguimiento.as_view()), name='listar_seguimiento'),
    url(r'^seguimiento/(?P<pk>\d+)/$', login_required(Seguimiento.as_view()), name='seguimiento'),
]



# urlpatterns = [
    # url(r'^nuevo$', tramite_view, name='tramite_crear'),
    # url(r'^listar_ingresados$', tramite_list_ingresados, name='tramite_listar_ingresados'),
    # url(r'^seguimiento/(?P<fk>\d+)/$', seguimiento_view, name='seguimiento_crear'),
    # url(r'^buscar$', tramite_search.as_view(), name='buscar_tramite'),
    # url(r'^list_tramite_subjects$', tramite_encontrar.as_view(), name='list_tramite_subjects'),
# ]

sit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.urls import path
from django.contrib.auth.views import login, logout_then_login

from django.contrib.auth.decorators import login_required
from apps.tramite.home import Index
from axes.decorators import watch_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', (Index.as_view()), name='home'),
    url(r'^tramite/', include('apps.tramite.urls', namespace="tramite")),
    url(r'^vehiculo/', include('apps.vehiculo.urls', namespace="vehiculo")),
    url(r'^operador/', include('apps.operario.urls', namespace="operario")),
    url(r'^tecnico/', include('apps.tecnico.urls', namespace="tecnico")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # url(r'^accounts/login/', login,{'template_name':'index.html'}, name='login'),
    url(r'^accounts/login/$', watch_login(login),{'template_name':'index.html'}, name='login'),
    url(r'^logout/', watch_login(logout_then_login), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

apps/tramite/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import models

#Importando la tabla de Usuarios de django
from django.contrib.auth.models import User

from apps.tecnico.models import Operador_Nuevo, Vehiculo_Nuevo

class Tramite(models.Model):
    tipo_tramite = models.CharField(max_length=50, null=True, blank=True, default="EXTENSION TARJETA DE OPERACION INTERPROVINCIAL")
    solicitante = models.ForeignKey(Operador_Nuevo, null=True, blank=True, on_delete=models.CASCADE)
    fecha_ingreso = models.DateField(null=True, blank=True)
    hora_ingreso = models.TimeField(null=True, blank=True)
    num_fojas = models.IntegerField(null=True, blank=True)
    estado = models.CharField(max_length=10, null=True, blank=True)
    observaciones = models.TextField(null=True, blank=True, default="EXTENSION DE TARJETAS DE OPERACIONES")
    baja_observacion = models.TextField(null=True, blank=True)

    tiene_orden = models.BooleanField(default=False)
    finalizar = models.BooleanField(default=False)
    finalizado = models.BooleanField(default=False)
    vigente = models.BooleanField(default=True) # Para saber cual fue el ultimo tramite que realizó el operador

    asignar_v = models.ManyToManyField(Vehiculo_Nuevo, through = 'Asignar_Vehiculo', related_name = 'tramite')
    class Meta:
        permissions=(
            ('administrar_tramite', 'Puede administrar tramites'),
        )

    def __unicode__(self):
        return '{} / {}'.format(self.solicitante, self.fecha_ingreso)

class Asignar_Vehiculo(models.Model):
    tramite = models.ForeignKey(Tramite, null=True, blank=True, on_delete=models.CASCADE, related_name = 'asignar')
    vehiculo = models.ForeignKey(Vehiculo_Nuevo, null=True, blank=True, on_delete=models.CASCADE, related_name = 'asig_vehiculo')
    validez = models.IntegerField(null=True, blank=True, default=1)
    gestion = models.IntegerField(null=True, blank=True)
    monto = models.IntegerField(null=True, blank=True)
    valida_del = models.DateField(null=True, blank=True)
    valida_al = models.DateField(null=True, blank=True)
    # variables de control
    tiene_tarjeta = models.BooleanField(default=False)  #para saber si la tarjeta fue impresa
    caducado = models.BooleanField(default=False) #para saber si la tarjeta caducó luego del año de validez
    
    def __unicode__(self):
        return '{} / {} / {}'.format(self.tramite, self.vehiculo, self.gestion)

templates/tramite/asignar_vehiculos.html
{% extends "base/base_site.html" %}
{% load staticfiles %}
{% block title %} Asignar Vehiculos {% endblock title %}

{% block content %}
<div class="right_col" role="main">
    <a class="btn btn-primary" href="{% url 'tramite:listar_tramite' %}"> <i class="fa fa-backward"></i>Volver</a>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">  
                <div class="x_title">
                    <h2>DETALLE DEL TRÁMITE Nro {{ object.id }}</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Settings 1</a></li>
                                <li><a href="#">Settings 2</a></li>
                            </ul>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="form-group form-horizontal col-md-4 col-sm-12 col-xs-12">
                        <label class="control-label col-md-5 col-sm-6 col-xs-12">NUMERO DE TRÁMITE</label>
                        <div class="col-md-7 col-sm-4 col-xs-12">
                            <input type="text" disabled="disabled" placeholder="{{ object.id }}">
                        </div>
                    </div>
                    <div class="form-group form-horizontal col-md-8 col-sm-12 col-xs-12">
                        <label class="control-label col-md-2 col-sm-6 col-xs-12">TIPO DE TRÁMITE</label>
                        <div class="col-md-10 col-sm-6 col-xs-12">
                            <input class="col-md-10" type="text" disabled="disabled" placeholder="{{ object.tipo_tramite }}">
                        </div>
                    </div>
                    <div class="form-group form-horizontal col-md-4 col-sm-12 col-xs-12">
                        <label class="control-label col-md-5 col-sm-6 col-xs-12">SOLICITANTE</label>
                        <div class="col-md-7 col-sm-4 col-xs-12">
                            <input type="text" disabled="disabled" placeholder="{{ object.solicitante }}">
                        </div>
                    </div>
                    <div class="form-group form-horizontal col-md-8 col-sm-12 col-xs-12">
                        <label class="control-label col-md-2 col-sm-6 col-xs-12">FECHA INGRASADO</label>
                        <div class="col-md-10 col-sm-6 col-xs-12">
                            <input class="col-md-10" type="text" disabled="disabled" placeholder="{{ object.fecha_ingreso }}">
                        </div>
                    </div>
                    <div class="form-group form-horizontal col-md-4 col-sm-12 col-xs-12">
                        <label class="control-label col-md-5 col-sm-6 col-xs-12">ESTADO</label>
                        <div class="col-md-7 col-sm-4 col-xs-12">
                            <input type="text" disabled="disabled" placeholder="{{ object.estado }}">
                        </div>
                    </div>
                    <div class="form-group form-horizontal col-md-8 col-sm-12 col-xs-12">
                        <label class="control-label col-md-2 col-sm-6 col-xs-12">NUMERO DE FOJAS</label>
                        <div class="col-md-10 col-sm-6 col-xs-12">
                            <input class="col-md-10" type="text" disabled="disabled" placeholder="{{ object.num_fojas }}">
                        </div>
                    </div>
                    <div class="form-group form-horizontal col-md-8 col-sm-12 col-xs-12">
                        <label class="control-label col-md-3 col-sm-6 col-xs-12">ASIGNAR VEHICULOS</label>
                        <div class="fa-hover">
                            <a class="btn btn-primary" data-toggle="tooltip" title="Registrar Vehiculo" href="{% url 'tramite:asignar_vehiculo' pk=object.id %}"><i class="fa fa-plus-square"></i></a>
                        </div>
                        <br>
                        <div class="scrollable" style="height: 200px; overflow: scroll">    
                            <table id="datatable" style="margin-top:1em" class="table table-striped table-bordered col-md-5 col-sm-6 col-xs-12">
                                <thead>
                                    <tr> 
                                        <th>Placa</th>
                                        <th>Propietario</th>
                                        <th>Tipo</th>
                                        <th>Marca</th>
                                        <th>Modelo</th>
                                        <th>Acción</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if vehiculos_asignados %}
                                        {% for asignado in vehiculos_asignados %}
                                        <tr>
                                            <td>{{ asignado.vehiculo.placa }}</td>
                                            <td>{{ asignado.vehiculo.propietario }}</td>
                                            <td>{{ asignado.vehiculo.tipo_vehiculo }}</td>
                                            <td>{{ asignado.vehiculo.marca }}</td>
                                            <td>{{ asignado.vehiculo.modelo }}</td>
                                            <td>
                                                <a class="btn btn-danger btn-xs " data-toggle="tooltip" title="Eliminar Asignación" href="{% url 'tramite:eliminar_asignacion' pk=asignado.id fk=object.id %}"><i class="fa fa-trash"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    {% else %}
                                    <tr>
                                        <td colspan="6">
                                            <h4 style="color: red">EL TRÁMITE AÚN NO TIENE VEHÍCULOS ASIGNADOS</h4>
                                        </td>
                                    </tr>
                                    {% endif %}
                                </tbody>
                            </table>
                        </div>
                        <br>
                        <a class="btn btn-success" id="procesar" href="#">Proceder con el trámite</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <form action="{% url 'tramite:tramite_proceso' pk=object.id %}" method="POST" id="proceso">
        {% csrf_token %}
    </form>
    <!-- Modal Registrar Ruta -->
    <div id="modal-ruta" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <form id="form-ruta-operador" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span></button>
                            <h4 class="modal-title" id="myModalLabel">Asignar Vehículo</h4>
                        </div>
                        <div class="modal-body">
                            <div class="item form-group col-md-6 col-sm-12 col-xs-12">    
                                <label class="control-label col-md-4 col-sm-6 col-xs-12">{{formulario.vehiculo.label}}</label>
                                <div class="col-md-8 col-sm-6 col-xs-12">
                                    {{vehiculos}}
                                </div>
                            </div>
                            <div class="form-group col-md-6 col-sm-12 col-xs-12">
                                <label class="control-label col-md-3 col-sm-6 col-xs-12">{{formulario.validez.label}}</label>
                                <div class="col-md-9 col-sm-6 col-xs-12">
                                    {{formulario.validez}}
                                </div>
                            </div>
                            <div class="item form-group col-md-6 col-sm-12 col-xs-12">    
                                <label class="control-label col-md-4 col-sm-6 col-xs-12">{{formulario.monto.label}}</label>
                                <div class="col-md-8 col-sm-6 col-xs-12">
                                    {{formulario.monto}}
                                </div>
                            </div>
                            <div class="form-group col-md-6 col-sm-12 col-xs-12">
                                <label class="control-label col-md-3 col-sm-6 col-xs-12">{{formulario.gestion.label}}</label>
                                <div class="col-md-9 col-sm-6 col-xs-12">
                                    {{formulario.gestion}}
                                </div> 
                            </div>
                            <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar Ventana</button>
                                <button type="submit" class="btn btn-primary">Guardar</button>
                            </div>
                        </div>
                    </form>
                    <div class="modal-footer"></div>
                </div>
            </div>
        </div>
        <!-- /modals -->
</div>

{% endblock content %}
{% block javascripts %}
  {{ block.super }}
  <script src="/static/js/project.js"></script>
  <!-- validator -->
  <script src="/static/vendors/validator/validator.js"></script>
  <script>

        // script modal registrar ruta
        $("#btn-add-ruta").on("click", function(){
            var id_operador = $(this).attr("operador");
            $("#form-ruta-operador").attr("action", "/operador/ruta/registrar/"+id_operador+"/");
            $("#modal-ruta").modal("show");
        });
        $('#procesar').on("click",function(){
            $("#proceso").submit();
        });

    </script>
{% endblock %}

templates/tramite/listar_seguimiento.html
{% extends "base/base_site.html" %}

{% block title %} Lista Operadores Renovar {% endblock title %}

{% block js %}

{% endblock js %}
 
{% block content %}
<div class="right_col" role="main">
    <!-- <a class="btn btn-primary" href="{% url 'tecnico:operador_renovavion_listar' %}"><i class="fa fa-backward"></i> Volver</a> -->
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <h1>SEGUIMIENTO A OPERADORES EN TRÁMITE</h1>
            <br>
            <div class="scrollable" style="height: 440px; overflow: scroll">
                <!-- <table class="table table-striped table-bordered prueba dt-responsive display nowrap jambo_table" cellpadding="0" width="100%" height= "300px"> -->
                <table id="myTable" class="table table-striped table-bordered prueba dt-responsive display nowrap jambo_table" cellpadding="0" width="100%" height= "300px">
                    <thead>
                    <tr class="headings" >
                        <th  style="width: 15%;">SEGUIMIENTO</th>
                        <th  style="width: 55%;">NOMBRE <input type="text" id="myInput" onkeyup="searchOperadorForName()" placeholder=" Buscar por nombre..." title="Type in a name"></th>
                        <th  style="width: 30%;">RAZON SOCIAL</th>
                    </tr>
                    </thead>
                    <tbody id="tablita">
                        {% if operadores %}
                        {% for operador in operadores %}
                        <tr>
                            <td>
                                {% if operador.en_tramite %}
                                <a class="btn btn-success" href="{% url 'tramite:seguimiento' pk=operador.id %}">Ver estado</a>
                                {% endif %}
                            </td>
                            <td>{{ operador.nombre }}</td>
                            <td>{{ operador.razon_social }}</td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <tr>
                            <td colspan="3">
                                <h2>No hay registros de Operadores Con trámite en curso</h2>
                            </td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


</div>
{% endblock content %}
{% block javascripts %}
{{ block.super }}
<script src="/static/js/project.js"></script>
<script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
<script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
<script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="/static/js/responsive.bootstrap.js"></script>
<script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
<!-- validator -->
<script src="/static/vendors/validator/validator.js"></script>
<script type="text/javascript">

    function searchOperadorForName() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        // let txt = 'No se encontro ninguna coincidencia...';
        // var fila="<tr><td colspan='3'>"+ txt +"</td></tr>";
        // var btn = document.createElement("TR");
        // btn.innerHTML=fila;
        // document.getElementById("tablita").appendChild(btn);
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[1];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                tr[i].style.display = "none";
                }
            }
        }
    }

</script>
<style type="text/css">
#myInput {
  /* background-image: url('/css/searchicon.png');
  background-position: 10px 10px;
  background-repeat: no-repeat; */
  background-color: rgb(150, 182, 252);
  width: 50%;
  font-size: 15px;
  color: rgb(255, 255, 255);
  border: 1px solid rgb(36, 69, 107);
  border-radius: 0 3px;
}
</style>
{% endblock %}